-- liquibase formatted sql

-- changeset author:1
CREATE TABLE "user"
(
    id            BIGSERIAL PRIMARY KEY,
    username      VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(60)  NOT NULL,
    roles         VARCHAR(255) NOT NULL,
    date          DATE         NOT NULL
);

-- changeset author:2
CREATE TABLE recipe
(
    id               BIGSERIAL PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    image            TEXT         NOT NULL,
    description      TEXT         NOT NULL,
    recette          TEXT         NOT NULL,
    preparation_time FLOAT        NOT NULL,
    nb_persons       INT          NOT NULL,
    difficulty       FLOAT        NOT NULL,
    tags             TEXT         NOT NULL,
    author_id        BIGINT       NOT NULL,
    date             DATE         NOT NULL,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES "user" (id)
);

-- changeset author:3
CREATE TABLE recipeRatings
(
    id       BIGSERIAL PRIMARY KEY,
    userId   BIGINT NOT NULL,
    recipeId BIGINT NOT NULL,
    rating   FLOAT,
    CONSTRAINT fk_userId FOREIGN KEY (userId) REFERENCES "user" (id),
    CONSTRAINT fk_recipeId FOREIGN KEY (recipeId) REFERENCES recipe (id)
);

-- changeset author:4
INSERT INTO "user" (username, password_hash, roles, date)
VALUES ('JeanDupont', 'hashed_password1', 'USER', '2023-10-23'),
       ('MarieMartin', 'hashed_password2', 'USER', '2023-10-23'),
       ('PierreDurand', 'hashed_password3', 'USER', '2023-10-23'),
       ('SophieLefevre', 'hashed_password4', 'USER', '2023-10-23'),
       ('LucieMoreau', 'hashed_password5', 'USER', '2023-10-23');

-- changeset author:5
INSERT INTO recipe (title, image, description, recette, preparation_time, nb_persons, difficulty, tags, author_id, date)
VALUES ('Soupe à lail', 'https://example.com/image1.jpg', 'Délicieuse soupe française à lail.',
        '{"ingredients": ["Oignons", "Bouillon", "Pain grillé"], "instructions": ["Faire revenir les oignons.", "Ajouter le bouillon et mijoter."]}',
        1.2, 2, 3.4, '["végé", "miam"]', 1, '2023-10-23'),
       ('Quiche Lorraine', 'https://example.com/image2.jpg', 'Une classique quiche lorraine.',
        '{"ingredients": ["Crème", "Œufs", "Bacon"], "instructions": ["Préchauffer le four.", "Préparer la pâte.", "Cuire au four."]}',
        1.5, 4, 2.5, '["salé", "tradition"]', 2, '2023-10-23'),
       ('Tarte aux pommes', 'https://example.com/image3.jpg', 'Un dessert incontournable.',
        '{"ingredients": ["Pommes", "Pâte brisée", "Sucre"], "instructions": ["Préparer la pâte.", "Disposer les pommes.", "Enfourner."]}',
        2.0, 6, 2.0, '["sucré", "fruit"]', 3, '2023-10-23'),
       ('Ratatouille', 'https://example.com/image4.jpg', 'Un mélange de légumes frais.',
        '{"ingredients": ["Aubergines", "Courgettes", "Tomates"], "instructions": ["Faire revenir les légumes.", "Laisser mijoter."]}',
        1.8, 3, 4.0, '["végé", "tradition"]', 4, '2023-10-23'),
       ('Boeuf Bourguignon', 'https://example.com/image5.jpg', 'Un plat riche et savoureux.',
        '{"ingredients": ["Bœuf", "Vin rouge", "Carottes"], "instructions": ["Faire revenir le bœuf.", "Ajouter les légumes.", "Laisser mijoter longtemps."]}',
        3.5, 4, 5.0, '["carné", "gourmand"]', 5, '2023-10-23'),
       ('Croissants au beurre', 'https://example.com/croissants.jpg',
        'Des croissants feuilletés au beurre, parfaits pour le petit déjeuner.',
        '{"ingredients": ["Farine", "Beurre", "Lait", "Levure"], "instructions": ["Mélanger la farine et la levure.", "Incorporer le beurre en couches.", "Laisser reposer et cuire au four."]}',
        4.0, 8, 4.5, '["sucré", "boulangerie"]', 1, '2023-10-23'),
       ('Salade Niçoise', 'https://example.com/salade-nicoise.jpg',
        'Une salade classique avec des légumes frais, du thon et des œufs durs.',
        '{"ingredients": ["Tomates", "Haricots verts", "Thon", "Œufs"], "instructions": ["Cuire les haricots.", "Assembler les légumes et le thon.", "Assaisonner avec de lhuile dolive."]}',
        1.0, 2, 2.0, '["végé", "léger"]', 2, '2023-10-23'),
       ('Coq au vin', 'https://example.com/coq-au-vin.jpg',
        'Un plat français riche à base de coq mijoté dans du vin rouge.',
        '{"ingredients": ["Coq", "Vin rouge", "Champignons", "Oignons"], "instructions": ["Faire revenir le coq.", "Ajouter les légumes et le vin.", "Laisser mijoter longtemps."]}',
        3.0, 4, 5.0, '["carné", "tradition"]', 3, '2023-10-23'),
       ('Crêpes Suzette', 'https://example.com/crepes-suzette.jpg',
        'Des crêpes fines servies avec une sauce à lorange flambée.',
        '{"ingredients": ["Farine", "Lait", "Œufs", "Oranges", "Grand Marnier"], "instructions": ["Préparer la pâte à crêpes.", "Faire les crêpes.", "Préparer la sauce à lorange et flamber."]}',
        1.5, 6, 3.0, '["sucré", "dessert"]', 4, '2023-10-23'),
       ('Tartiflette', 'https://example.com/tartiflette.jpg',
        'Un plat savoyard à base de pommes de terre, de fromage reblochon et de lardons.',
        '{"ingredients": ["Pommes de terre", "Reblochon", "Lardons", "Oignons"], "instructions": ["Faire cuire les pommes de terre.", "Faire revenir les lardons et oignons.", "Assembler avec le reblochon et cuire au four."]}',
        2.0, 4, 4.0, '["carné", "fromage", "montagne"]', 5, '2023-10-23'),
       ('Poulet Basquaise', 'https://example.com/poulet-basquaise.jpg',
        'Un poulet mijoté avec des poivrons et des tomates, spécialité du Pays basque.',
        '{"ingredients": ["Poulet", "Poivrons", "Tomates", "Oignons"], "instructions": ["Faire revenir le poulet.", "Ajouter les légumes et mijoter à feu doux."]}',
        2.5, 4, 3.8, '["carné", "légumes", "tradition"]', 1, '2023-10-23'),
       ('Clafoutis aux cerises', 'https://example.com/clafoutis.jpg',
        'Un dessert traditionnel français à base de cerises cuites dans une pâte à crêpe.',
        '{"ingredients": ["Cerises", "Farine", "Lait", "Œufs", "Sucre"], "instructions": ["Préparer la pâte.", "Disposer les cerises et enfourner."]}',
        1.0, 6, 2.5, '["sucré", "fruit"]', 2, '2023-10-23'),
       ('Bœuf Stroganoff', 'https://example.com/boeuf-stroganoff.jpg',
        'Un plat russe à base de bœuf en sauce à la crème et aux champignons.',
        '{"ingredients": ["Bœuf", "Crème fraîche", "Champignons", "Oignons"], "instructions": ["Faire revenir le bœuf.", "Ajouter la crème et les champignons.", "Laisser mijoter doucement."]}',
        2.0, 4, 4.0, '["carné", "crémeux", "tradition"]', 3, '2023-10-23'),
       ('Crème brûlée', 'https://example.com/creme-brulee.jpg',
        'Un dessert classique à base de crème vanillée et d’une fine couche de caramel croquant.',
        '{"ingredients": ["Crème", "Sucre", "Vanille", "Œufs"], "instructions": ["Préparer la crème.", "Cuire au four et caraméliser le dessus."]}',
        1.5, 4, 3.0, '["sucré", "dessert", "vanille"]', 4, '2023-10-23'),
       ('Bouillabaisse', 'https://example.com/bouillabaisse.jpg', 'Une soupe de poisson provençale parfumée au safran.',
        '{"ingredients": ["Poisson", "Safran", "Tomates", "Ail"], "instructions": ["Préparer un bouillon avec le poisson.", "Ajouter les épices et laisser mijoter."]}',
        3.5, 6, 4.5, '["poisson", "tradition", "méditerranée"]', 5, '2023-10-23'),
       ('Rillettes de saumon', 'https://example.com/rillettes-saumon.jpg',
        'Un apéritif frais à base de saumon cuit et de fromage frais.',
        '{"ingredients": ["Saumon", "Fromage frais", "Ciboulette", "Citron"], "instructions": ["Cuire le saumon.", "Mélanger avec le fromage et la ciboulette."]}',
        0.8, 4, 2.0, '["poisson", "léger", "apéro"]', 1, '2023-10-23'),
       ('Tarte Tatin', 'https://example.com/tarte-tatin.jpg',
        'Une tarte renversée aux pommes caramélisées, un grand classique français.',
        '{"ingredients": ["Pommes", "Sucre", "Pâte brisée", "Beurre"], "instructions": ["Caraméliser les pommes.", "Recouvrir avec la pâte et cuire au four."]}',
        1.5, 6, 3.0, '["sucré", "dessert", "fruit"]', 2, '2023-10-23'),
       ('Escargots de Bourgogne', 'https://example.com/escargots.jpg',
        'Des escargots cuits avec une sauce au beurre persillé.',
        '{"ingredients": ["Escargots", "Beurre", "Ail", "Persil"], "instructions": ["Préparer les escargots.", "Faire fondre le beurre avec l ail et le persil.", "Cuire les escargots dans la sauce."]}',
        1.0, 4, 4.0, '["carné", "tradition", "apéritif"]', 3, '2023-10-23'),
       ('Ragoût de mouton', 'https://example.com/ragout-mouton.jpg',
        'Un ragoût riche et savoureux à base de mouton et de légumes.',
        '{"ingredients": ["Mouton", "Carottes", "Pommes de terre", "Oignons"], "instructions": ["Faire revenir la viande.", "Ajouter les légumes et mijoter longtemps."]}',
        3.0, 5, 4.5, '["carné", "tradition", "légumes"]', 4, '2023-10-23'),
       ('Macarons', 'https://example.com/macarons.jpg',
        'De petits biscuits français délicats à base de poudre d’amandes, fourrés de ganache.',
        '{"ingredients": ["Poudre d amandes", "Sucre", "Œufs", "Ganache"], "instructions": ["Préparer les coques de macarons.", "Préparer la ganache et assembler."]}',
        2.0, 8, 4.8, '["sucré", "dessert", "fête"]', 5, '2023-10-23'),
       ('Sablés au parmesan et romarin', 'https://example.com/sables-parmesan.jpg',
        'Des biscuits salés croustillants au parmesan et au romarin, parfaits pour lapéritif.',
        '{"ingredients": ["Parmesan", "Farine", "Beurre", "Romarin"], "instructions": ["Mélanger la farine et le parmesan.", "Ajouter le beurre et le romarin.", "Former des sablés et cuire au four."]}',
        0.75, 20, 2.0, '["apéritif", "salé", "fromage"]', 1, '2023-10-23'),
       ('Risotto à la truffe noire', 'https://example.com/risotto-truffe.jpg',
        'Un risotto crémeux au parmesan, sublimé par des lamelles de truffe noire.',
        '{"ingredients": ["Riz arborio", "Bouillon", "Parmesan", "Truffe noire"], "instructions": ["Faire revenir le riz.", "Ajouter le bouillon progressivement.", "Incorporer le parmesan et les truffes."]}',
        1.5, 4, 4.0, '["italien", "gourmet", "luxe"]', 2, '2023-10-23'),
       ('Curry de lentilles corail', 'https://example.com/curry-lentilles.jpg',
        'Un plat végétarien épicé à base de lentilles corail, lait de coco et épices indiennes.',
        '{"ingredients": ["Lentilles corail", "Lait de coco", "Épices", "Oignons"], "instructions": ["Faire revenir les oignons avec les épices.", "Ajouter les lentilles et le lait de coco.", "Laisser mijoter jusquà cuisson complète."]}',
        1.0, 4, 3.0, '["végé", "épicé", "indien"]', 3, '2023-10-23'),
       ('Tagliatelles au pesto de basilic et noix', 'https://example.com/tagliatelles-pesto.jpg',
        'Des pâtes fraîches accompagnées dun pesto de basilic et de noix maison.',
        '{"ingredients": ["Tagliatelles", "Basilic", "Noix", "Ail", "Parmesan"], "instructions": ["Préparer le pesto en mixant basilic, noix et ail.", "Cuire les tagliatelles et mélanger avec le pesto."]}',
        0.8, 4, 2.5, '["italien", "végé", "rapide"]', 4, '2023-10-23'),
       ('Tarte aux poires et chocolat', 'https://example.com/tarte-poires-chocolat.jpg',
        'Une tarte gourmande associant la douceur des poires et lintensité du chocolat noir.',
        '{"ingredients": ["Poires", "Chocolat noir", "Pâte sablée", "Crème fraîche"], "instructions": ["Faire fondre le chocolat.", "Disposer les poires sur la pâte.", "Ajouter le chocolat fondu et enfourner."]}',
        1.2, 6, 3.0, '["dessert", "fruit", "gourmand"]', 5, '2023-10-23'),
       ('Soufflé au fromage de chèvre et ciboulette', 'https://example.com/souffle-chevre.jpg',
        'Un soufflé aérien au fromage de chèvre et à la ciboulette fraîche.',
        '{"ingredients": ["Fromage de chèvre", "Œufs", "Beurre", "Ciboulette"], "instructions": ["Préparer la béchamel.", "Incorporer le fromage et la ciboulette.", "Monter les blancs en neige et enfourner."]}',
        1.0, 4, 4.2, '["fromage", "gourmet", "français"]', 1, '2023-10-23'),
       ('Boulettes de viande à la sauce tomate épicée', 'https://example.com/boulettes-tomate.jpg',
        'Des boulettes de viande savoureuses mijotées dans une sauce tomate légèrement épicée.',
        '{"ingredients": ["Viande hachée", "Tomates", "Épices", "Oignons"], "instructions": ["Préparer les boulettes.", "Faire mijoter dans la sauce tomate avec les épices."]}',
        1.2, 4, 3.5, '["carné", "épicé", "classique"]', 2, '2023-10-23'),
       ('Poulet tikka masala', 'https://example.com/tikka-masala.jpg',
        'Un curry indien onctueux à base de poulet mariné dans des épices et du yaourt.',
        '{"ingredients": ["Poulet", "Yaourt", "Épices", "Tomates"], "instructions": ["Mariner le poulet dans le yaourt et les épices.", "Faire mijoter dans la sauce tomate et servir avec du riz."]}',
        2.0, 4, 4.5, '["indien", "curry", "poulet", "épicé"]', 3, '2023-10-23'),
       ('Quinoa aux légumes rôtis', 'https://example.com/quinoa-legumes.jpg',
        'Un plat sain et nourrissant à base de quinoa et de légumes rôtis.',
        '{"ingredients": ["Quinoa", "Courgettes", "Poivrons", "Aubergines"], "instructions": ["Faire cuire le quinoa.", "Rôtir les légumes au four avec des herbes.", "Mélanger le tout et servir chaud."]}',
        1.0, 4, 2.0, '["végé", "sain", "rapide"]', 4, '2023-10-23'),
       ('Gâteau fondant au chocolat et piment dEspelette', 'https://example.com/gateau-chocolat.jpg',
        'Un fondant au chocolat noir relevé par une pointe de piment dEspelette pour un twist épicé.',
        '{"ingredients": ["Chocolat noir", "Beurre", "Œufs", "Piment d Espelette"], "instructions": ["Faire fondre le chocolat.", "Ajouter le beurre et les œufs.", "Incorporer une pincée de piment d Espelette et cuire au four."]}',
        1.2, 8, 3.8, '["dessert", "chocolat", "épicé"]', 5, '2023-10-23');

-- changeset author:6
INSERT INTO recipeRatings (userId, recipeId, rating)
VALUES (1, 1, 4.5),
       (2, 2, 4.0),
       (3, 3, 5.0),
       (4, 4, 3.8),
       (5, 5, 4.9),
       (1, 6, 4.8),
       (2, 7, 3.5),
       (3, 8, 5.0),
       (4, 9, 4.2),
       (5, 10, 4.7),
       (1, 7, 4.0),
       (2, 9, 4.9),
       (3, 6, 4.5),
       (4, 8, 4.7),
       (5, 6, 4.6),
       (1, 11, 4.6),
       (2, 12, 4.0),
       (3, 13, 4.8),
       (4, 14, 5.0),
       (5, 15, 4.5),
       (1, 16, 3.9),
       (2, 17, 4.7),
       (3, 18, 3.8),
       (4, 19, 4.2),
       (5, 20, 5.0),
       (1, 21, 4.8),
       (2, 22, 5.0),
       (3, 23, 4.2),
       (4, 24, 4.0),
       (5, 25, 4.9),
       (1, 26, 4.7),
       (2, 27, 4.3),
       (3, 28, 4.5),
       (4, 29, 4.0),
       (5, 30, 5.0),
       (1, 2, 4.2),
       (2, 3, 4.6),
       (3, 4, 3.9),
       (4, 5, 4.8),
       (5, 1, 4.3),
       (1, 3, 4.9),
       (2, 4, 3.5),
       (3, 5, 5.0),
       (4, 1, 4.4),
       (5, 2, 4.6),
       (1, 8, 4.1),
       (2, 9, 4.5),
       (3, 10, 4.7),
       (4, 6, 4.3),
       (5, 7, 3.8),
       (1, 15, 4.7),
       (2, 11, 4.5),
       (3, 12, 4.9),
       (4, 14, 4.3),
       (5, 13, 4.6);